from pathlib import Path
from typing import Any, Dict


try:
    import tomllib  # type: ignore[attr-defined]
except ModuleNotFoundError:  # pragma: no cover - Python 3.9 fallback
    tomllib = None  # type: ignore[assignment]


def load_toml(path: Path) -> Dict[str, Any]:
    """Load a small TOML file.

    Python 3.11+ uses tomllib. Python 3.9 can still read the profile files generated by
    this project through a deliberately small parser for strings, booleans, numbers, lists,
    and one-level tables.
    """
    if not path.exists():
        return {}
    if tomllib is not None:
        with path.open("rb") as handle:
            return tomllib.load(handle)
    return _load_small_toml(path.read_text(encoding="utf-8"))


def dump_toml(data: Dict[str, Any]) -> str:
    lines = []
    for key, value in data.items():
        if isinstance(value, dict):
            lines.append(f"[{key}]")
            for nested_key, nested_value in value.items():
                lines.append(f"{nested_key} = {_format_value(nested_value)}")
            lines.append("")
        else:
            lines.append(f"{key} = {_format_value(value)}")
    return "\n".join(lines).rstrip() + "\n"


def _format_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_format_value(item) for item in value) + "]"
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _load_small_toml(text: str) -> Dict[str, Any]:
    data: Dict[str, Any] = {}
    section: Dict[str, Any] = data
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            section_name = line[1:-1].strip()
            section = {}
            data[section_name] = section
            continue
        if "=" not in line:
            continue
        key, raw_value = line.split("=", 1)
        section[key.strip()] = _parse_value(raw_value.strip())
    return data


def _parse_value(raw: str) -> Any:
    if raw in {"true", "false"}:
        return raw == "true"
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        if not inner:
            return []
        return [_parse_value(part.strip()) for part in inner.split(",")]
    if raw.startswith('"') and raw.endswith('"'):
        return raw[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    try:
        if "." in raw:
            return float(raw)
        return int(raw)
    except ValueError:
        return raw
